name: Dansdata
# DSN (Database Source Name) to connect database
dsn: postgresql://postgres:postgres@localhost:54322/postgres?sslmode=disable
docPath: docs/database
disableOutputSchema: true
format:
  # Sort the order of table list and columns
  # Default is false
  sort: true
er:
  # ER diagram image format
  # Default is `svg`
  # ---
  # Use png to make output more accessible
  format: png
  # Add table/column comment to ER diagram
  # Default is false
  comment: true
include:
  - auth.users
  - public.*
  - profiles.*
exclude:
  - auth.*
  - pgsodium.*
  - extensions.*
  - graphql.*
  - graphql_public.*
  - realtime.*
  - storage.*
