name: Dansdata
# DSN (Database Source Name) to connect database
dsn: postgresql://postgres:postgres@localhost:54322/postgres?sslmode=disable
docPath: docs/database
format:
  # Sort the order of table list and columns
  # Default is false
  sort: true
er:
  # ER diagram image format
  # Default is `svg`
  # ---
  # Use png to make output more accessible
  format: png
  # Add table/column comment to ER diagram
  # Default is false
  comment: true
# Waiting for answers to https://github.com/k1LoW/tbls/issues/369
# in order to replace specific selectors with wildcards.
exclude:
  - auth.audit_log_entries
  - auth.identities
  - auth.instances
  - auth.refresh_tokens
  - auth.schema_migrations
  - auth.sessions
  - pgsodium.*
  - extensions.*
  - graphql.*
  - graphql_public.*
  - realtime.*
  - storage.*
