name: dansdata_portal
description: "Dansdataportalen låter dig administrera dina evenemang och annat innehåll i Dansdatas databas."
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  get_it: ^7.6.6
  go_router: ^13.0.1
  intl: any
  logger: ^2.0.2+1
  signals: ^3.0.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icon/

  fonts:
    - family: Norican
      fonts:
        - asset: assets/fonts/Norican-Regular.ttf
    - family: RobotoFlex
      fonts:
        - asset: assets/fonts/RobotoFlex-VariableFont_GRAD,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,opsz,slnt,wdth,wght.ttf
