name: dansdata_portal
description: "Dansdataportalen låter dig administrera dina evenemang och annat innehåll i Dansdatas databas."
publish_to: none
version: 0.0.1+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_analytics: ^10.8.0
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  firebase_performance: ^0.9.3+8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  get_it: ^7.6.6
  go_router: ^13.0.1
  # Temporarily use git version until PR
  # [#408](https://github.com/Milad-Akarie/injectable/pull/408)
  # is merged.
  #  injectable: ^2.3.2
  injectable:
    git:
      url: https://github.com/FelixZY/injectable.git
      path: injectable
      ref: fix-singleton-environment-filter
  intl: any
  logger: ^2.0.2+1
  signals: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  # Temporarily use git version until PR
  # [#408](https://github.com/Milad-Akarie/injectable/pull/408)
  # is merged.
  #  injectable_generator: ^2.4.1
  injectable_generator:
    git:
      url: https://github.com/FelixZY/injectable.git
      path: injectable_generator
      ref: fix-singleton-environment-filter
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icon/

  fonts:
    - family: Norican
      fonts:
        - asset: assets/fonts/Norican-Regular.ttf
    - family: RobotoFlex
      fonts:
        - asset: assets/fonts/RobotoFlex-VariableFont_GRAD,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,opsz,slnt,wdth,wght.ttf
