import LanguageButton from "components/Button/Language";
import type { NextPage } from "next";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const router = useRouter();
  const { t } = useTranslation("common");
  return (
    <div className={styles.container + " flex flex-col h-full"}>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
      </Head>

      <main className={styles.main + " prose flex-grow"}>
        <h1 className="text-primary">{t("Hello World")}</h1>
        <LanguageButton variant="text" />
      </main>

      <footer className={styles.footer + " text-center flex-grow-0"}>
        <p>
          Version:{" "}
          <a
            className="text-primary"
            href={`https://github.com/dansdata-se/portal/tree/${process.env.NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA}`}
            target="_blank"
            rel="noopener noreferrer"
          >
            {process.env.NEXT_PUBLIC_VERCEL_GIT_COMMIT_REF}:
            {process.env.NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA?.substring(0, 7)}
          </a>
        </p>
      </footer>
    </div>
  );
};

export async function getStaticProps({ locale }: { locale: string }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"])),
    },
  };
}

export default Home;
