-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.
CREATE TABLE IF NOT EXISTS internal.associations (
  association text COLLATE pg_catalog."default" NOT NULL CHECK (association = LOWER(association)),
  created_at timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'::text),
  CONSTRAINT associations_pkey PRIMARY KEY (association)
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS internal.associations OWNER TO postgres;

ALTER TABLE IF EXISTS internal.associations ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE internal.associations IS 'Listing of the different ways a profile may be associated with an event_slot';

CREATE TABLE IF NOT EXISTS internal.association_translations (
  id bigserial,
  association text COLLATE pg_catalog."default" NOT NULL,
  language_code text COLLATE pg_catalog."default" NOT NULL,
  title text COLLATE pg_catalog."default" NOT NULL,
  description text COLLATE pg_catalog."default" NOT NULL,
  CONSTRAINT association_translations_pkey PRIMARY KEY (id),
  CONSTRAINT association_translations_association_language_code_key UNIQUE (association, language_code),
  CONSTRAINT association_translations_association_fkey FOREIGN KEY (association) REFERENCES internal.associations (association) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT association_translations_language_code_fkey FOREIGN KEY (language_code) REFERENCES internal.languages (code) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE RESTRICT
)
TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS association_translations_title_gin_idx ON internal.association_translations USING GIN (title extensions.gin_trgm_ops);

ALTER TABLE IF EXISTS internal.association_translations OWNER TO postgres;

ALTER TABLE IF EXISTS internal.association_translations ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE internal.association_translations IS 'Localized texts to describe a given association in a human-readable way';

CREATE TABLE IF NOT EXISTS internal.event_slot_profile_associations (
  id bigserial,
  slot_id uuid NOT NULL,
  profile_id uuid NOT NULL,
  association text COLLATE pg_catalog."default" NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'::text),
  CONSTRAINT event_slot_profile_associations_pkey PRIMARY KEY (id),
  CONSTRAINT event_slot_profile_associations_slot_id_profile_id_association_key UNIQUE (slot_id, profile_id, association),
  CONSTRAINT event_slot_profile_associations_association_fkey FOREIGN KEY (association) REFERENCES internal.associations (association) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE RESTRICT,
  CONSTRAINT event_slot_profile_associations_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES internal.profiles (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT event_slot_profile_associations_slot_id_fkey FOREIGN KEY (slot_id) REFERENCES internal.event_slots (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS internal.event_slot_profile_associations OWNER TO postgres;

ALTER TABLE IF EXISTS internal.event_slot_profile_associations ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE internal.event_slot_profile_associations IS 'Relates profiles to event slots.';

COMMENT ON COLUMN internal.event_slot_profile_associations.association IS 'The role a given profile has in the context of the event slot.';

INSERT INTO internal.associations (
  association)
VALUES (
  'band'),
(
  'artist'),
(
  'instructor'),
(
  'venue'),
(
  'photographer'),
(
  'association'),
(
  'individual'),
(
  'organization');

INSERT INTO internal.association_translations (
  association,
  language_code,
  title,
  description)
VALUES (
  'band',
  'xx',
  'Band',
  'A group performing music at events.'),
(
  'band',
  'en',
  'Band',
  'A group performing music at events.'),
(
  'band',
  'sv',
  'Band',
  'En grupp som spelar musik vid evenemang.'),
(
  'artist',
  'xx',
  'Artist',
  'An individual musician or singer.'),
(
  'artist',
  'en',
  'Artist',
  'An individual musician or singer.'),
(
  'artist',
  'sv',
  'Artist',
  'En enskild individ som spelar musik eller sjunger.'),
(
  'instructor',
  'xx',
  'Instructor',
  'An instructor or teacher.'),
(
  'instructor',
  'en',
  'Instructor',
  'An instructor or teacher.'),
(
  'instructor',
  'sv',
  'Instruktör',
  'En instruktör eller lärare.'),
(
  'venue',
  'xx',
  'Venue',
  'A place, or group of places, where events can take place.'),
(
  'venue',
  'en',
  'Venue',
  'A place, or group of places, where events can take place.'),
(
  'venue',
  'sv',
  'Plats',
  'En plats, eller grupp av platser, där evenemang kan anordnas.'),
(
  'photographer',
  'xx',
  'Photographer',
  'An individual, or group of individuals, taking photos at events.'),
(
  'photographer',
  'en',
  'Photographer',
  'An individual, or group of individuals, taking photos at events.'),
(
  'photographer',
  'sv',
  'Fotograf',
  'En eller flera individer som fotograferar.'),
(
  'association',
  'xx',
  'Association',
  'An association (sv. "Förening"), e.g. a dance club/school'),
(
  'association',
  'en',
  'Association',
  'An association (sv. "Förening"), e.g. a dance club/school'),
(
  'association',
  'sv',
  'Förening',
  'En förening, t.ex. en dansklubb'),
(
  'individual',
  'xx',
  'Individual',
  'An individual who does not fit in any other category.'),
(
  'individual',
  'en',
  'Individual',
  'An individual who does not fit in any other category.'),
(
  'individual',
  'sv',
  'Individ',
  'En enskild individ som inte passar bättre i en annan kategori.'),
(
  'organization',
  'xx',
  'Organization',
  'An organization that does not fit in any other category'),
(
  'organization',
  'en',
  'Organization',
  'An organization that does not fit in any other category'),
(
  'organization',
  'sv',
  'Organisation',
  'En organisation som inte passar bättre i en annan kategori.');

