-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.
CREATE EXTENSION IF NOT EXISTS "postgis" WITH SCHEMA "extensions";

CREATE TABLE IF NOT EXISTS internal.venue_profiles (
  profile_id uuid NOT NULL,
  coordinates geometry(point, 4326) NOT NULL,
  CONSTRAINT venue_profiles_pkey PRIMARY KEY (profile_id),
  CONSTRAINT venue_profiles_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES auth.users (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS internal.venue_profiles OWNER TO postgres;

ALTER TABLE IF EXISTS internal.venue_profiles ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE internal.venue_profiles IS 'Contains the subset of profiles that are venues';

CREATE INDEX venue_profiles_coordinates_geom_idx ON internal.venue_profiles USING GIST (coordinates);

