-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.
CREATE TABLE IF NOT EXISTS public.test_table (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  CACHE 1),
  created_at timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'::text),
  CONSTRAINT test_table_pkey PRIMARY KEY (id))
TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.test_table OWNER TO postgres;

ALTER TABLE IF EXISTS public.test_table ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.test_table TO anon;

GRANT ALL ON TABLE public.test_table TO authenticated;

GRANT ALL ON TABLE public.test_table TO postgres;

GRANT ALL ON TABLE public.test_table TO service_role;

GRANT ALL ON TABLE public.test_table TO tokenauthed;

CREATE POLICY "Enable read access for authenticated users" ON public.test_table AS PERMISSIVE
  FOR SELECT TO "authenticated", "tokenauthed"
    USING (TRUE);

