name: CI

on:
  pull_request:
  workflow_dispatch:

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure CI Environment
        uses: ./.github/actions/configure_environment

      - name: Ensure `format` and `fix` commands do not apply code changes
        run: |
          npm run format
          npm run fix
          if [ "$(git diff --ignore-space-at-eol | wc -l)" -gt "0" ]; then
            echo "Detected code style issues. See status below:"
            git diff
            exit 1
          fi

      # Make sure supabase can start
      - name: Start Supabase local development setup
        run: supabase start

      # Note that supabase must be running for `tbls lint` to work!
      - name: Lint
        run: npm run lint

      # Note that supabase must be running for `tbls` to generate documenation!
      - name: Verify generated types are up-to-date
        run: |
          npm run docs
          if [ "$(git diff --ignore-space-at-eol | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure CI Environment
        uses: ./.github/actions/configure_environment

      - name: Run tests
        run: npm test
