name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    env:
      DEBIAN_FRONTEND: noninteractive
      POSTGRES_VERSION: 14
      SUPABASE_CLI_VERSION: 1.8.4
      TBLS_VERSION: 1.56.9

    steps:
      - uses: actions/checkout@v3

      - name: Run `npm ci`
        run: npm ci

      - name: Install pgformatter
        run: |
          sudo cp ./.devcontainer/pgdg.pref /etc/apt/preferences.d/pgdg.pref
          echo "deb http://apt.postgresql.org/pub/repos/apt jammy-pgdg main ${POSTGRES_VERSION}" | sudo tee -a /etc/apt/sources.list.d/pgdg.list >/dev/null
          curl -sL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg >/dev/null
          sudo apt-get update
          sudo apt-get -y install --no-install-recommends pgformatter

      - name: Verify formatting
        run: |
          npm run format
          if [ "$(git diff --ignore-space-at-eol | wc -l)" -gt "0" ]; then
            echo "Detected code style issues. See status below:"
            git diff
            exit 1
          fi

      - name: Install [tbls](https://github.com/k1LoW/tbls)
        run: |
          curl -sL https://github.com/k1LoW/tbls/releases/download/v${TBLS_VERSION}/tbls_${TBLS_VERSION}-1_amd64.deb --output /tmp/tbls.deb
          sudo dpkg -i /tmp/tbls.deb

      - uses: supabase/setup-cli@v1
        with:
          version: ${{ env.SUPABASE_CLI_VERSION }}

      - name: Start Supabase local development setup
        run: supabase start

      # Note that supabase must be running for `tbls lint` to work!
      - name: Lint
        run: npm run lint

      - name: Verify generated types are up-to-date
        run: |
          npm run docs
          if [ "$(git diff --ignore-space-at-eol | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi
